### ISSUE TITLE
Question about getServerSideProps

### ISSUE THREAD

**Issue by nekiro** [alexUXUI/component-data-fetching#5]
Hi, I found this repo from google and your blog post.

I have question about getServerSideProps in pages/
Am I forced to use that everywhere?
Because getServerSideProps  does not return data on the first render, but on the second instead, which does not update my page and "loading" state is eternal.

This is my page component.
```
export default function Index({ news }) {
  // const [news, error] = useSSE(async () => {
  //   return await fetchJson(`${server}/api/news`);
  // }, []);

  console.log(news);

  if (!news) {
    return <FloatingWindow header={'Loading...'}>Loading...</FloatingWindow>;
  }

  return (
    <>
      {news.map((post) => (
        ...
      ))}
    </>
  );
}

export const getServerSideProps = async () => {
  const news = await fetchJson(`${server}/api/news`);
  return {
    props: {
      news,
    },
  };
};
```

It prints twice, first is undefined, second is my data from api.
It works with SSE though.

**Comment by alexUXUI** [comment]
Hey! Thanks for opening this issue. Do you have a link to your code? Next.js does not require users to use any of the data loading methods, I think.
